# Site settings
author: Emmanuel Cole
title: Emmanuel's Blog
header-img: img/home-bg.png
email: emmanuel.c2011@gmail.com
copyright_name: Emmanuel Cole
description: > # this means to ignore newlines until "baseurl:"
  Observations, trouble shooting and applications of coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Emmanuelcole2017

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
